### PR TITLE
fix types for normalize products

### PR DESCRIPTION
**Pull request by CristianCucunuba**
Hey Loan, I fixed some of the types on the `normalize` file for the product functions, I tested the homepage and PDP and they seem to be working fine, although I can't add products to my cart yet. Will investigate why

Also `groupProductOptionsByAttributeLabel`  group the variants but not the `options` of the variants. So if a product with a variant has options we are not supporting them yet

### CODE REVIEW

**Comment by loan-laux** [comment]
Hey @CristianCucunuba, sorry I hadn't merged this and now it's out of sync... Would be great if you could resolve the conflicts whenever you get a chance. Thanks!

**Comment by CristianCucunuba** [comment]
sure will do tomorrow and also will take the chance to see all new features you implemented

**Comment by CristianCucunuba** [comment]
Hey @loan-laux merge conflicts are resolved, besides the types on the normalize product function, I added some extra types to the provider config for the new variables you added like `anonymousCartTokenCookie` `anonymousCartTokenCookieMaxAge` . Why did you add those? , I think the commerce provider has by default `cartCookie` and `cartCookieMaxAge` , we can't use those? 

I also added the `SHOP_ID` as an env var to avoid hardcoding it

**Comment by CristianCucunuba** [comment]
By the way I'm still unable to create a cart and test the other features, will dig on that more tomorrow but is throwing some error on the reaction API when trying to create it
image

**Comment by loan-laux** [comment]
@CristianCucunuba thank you so much for updating the PR! Updated types in that `normalize` file were overdue for sure.

> the new variables you added like anonymousCartTokenCookie anonymousCartTokenCookieMaxAge . Why did you add those? , I think the commerce provider has by default cartCookie and cartCookieMaxAge , we can't use those?

I thought I would give them better, more accurate names in the context of Reaction. From what I understand, you can name your config parameters however you want. These `cartCookie` and `cartCookieMaxAge` config params were named after Big Commerce concepts, if I'm not mistaken.

Since the cart API in Reaction needs an anonymous cart token (only for anonymous carts so we have to name it accordingly to avoid confusion) and a cart ID, I thought that was a bit different than how Big Commerce/Shopify work, and so it made sense to more accurately name them.

What do you think? Should we keep the default names instead in your opinion?

**Comment by CristianCucunuba** [comment]
I like better your approach of having more accurate names withing the context of reaction commerce provider, would make things more easier to debug, we would still need to include `cartCookie` and `cartCookieMaxAge` in the current typing implementation but that's okay

**Review by loan-laux — APPROVED** [review]

**Pull request merged**
